on: push
name: Validate, Build, and Publish
jobs:
  buildTestPublish:
    name: buildTestPublish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install Dependencies
        run: yarn install
      - name: Validate
        run: yarn validate
      - name: Build
        uses: yarn build
      - name: SemanticRelease
        if: github.event.ref == 'refs/heads/master'
        run: yarn semantic-release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
